### ISSUE TITLE
🚀 Feature: Skip dts generation in lint.yml's build

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/create-typescript-app#1162]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Right now, if a repo is created with the `bin` option, `lint.yml` will run a build before lint:

https://github.com/JoshuaKGoldberg/create-typescript-app/blob/c348a61315beba56f9059ae27541158754e9789d/.github/workflows/lint.yml#L7-L8

The only reason that happens is because the `n/no-missing-import` will report on the `bin` file pointing to a missing (not-yet-built) `.js` file.

There's no need to also generate TypeScript `.d.ts` files during build. Lint workflows in CI will be faster if the `dts` part of tsup is skipped.

### Additional Info

I tried using `pnpm build --dts false` or `pnpm run build --dts false`. But that seems to configure tsup to try to build the file/module `"false"`, not disable `dts`.

```plaintext
DTS Build start
RollupError: Could not resolve entry module "false".
    at Object.error (/Users/josh/repos/create-typescript-app/node_modules/.pnpm/rollup@4.5.1/node_modules/rollup/dist/shared/parseAst.js:279:30)
    at ModuleLoader.loadEntryModule (/Users/josh/repos/create-typescript-app/node_modules/.pnpm/rollup@4.5.1/node_modules/rollup/dist/shared/rollup.js:19030:32)
    at async Promise.all (index 0)
Error: error occured in dts build
    at Worker.<anonymous> (/Users/josh/repos/create-typescript-app/node_modules/.pnpm/tsup@8.0.1_typescript@5.3.3/node_modules/tsup/dist/index.js:2690:26)
    at Worker.emit (node:events:519:28)
    at MessagePort.<anonymous> (node:internal/worker:263:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:822:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
DTS Build error
 ELIFECYCLE  Command failed with exit code 1.
```

Filed https://github.com/egoist/tsup/issues/1070 to ask about this in tsup. Marking this issue as blocked for now.

Aside: I bet this could also be used in post-run cleanup too... see #1161.

**Comment by JoshuaKGoldberg** [comment]
Aha! Thanks @anubra266 -> https://github.com/chakra-ui/panda/pull/2016/files#r1454590849, TIL about `no-dts`!
