### ISSUE TITLE
🐛 Bug: Setup script crashes with 'Error writing structure'

### ISSUE THREAD

**Issue by lcforbes** [JoshuaKGoldberg/create-typescript-app#1195]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

You should be able to run 'npx create-typescript-app'.

### Actual

```
 Creating repository structure...
│   - Writing structure...│  ❌ Error writing structure > writing structure.
│
Error: Failed writing structure > writing structure
    at withSpinners (file:///C:/Users/leroy/AppData/Local/npm-cache/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/lib/shared/cli/spinners.js:32:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createWithOptions (file:///C:/Users/leroy/AppData/Local/npm-cache/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/lib/create/createWithOptions.js:12:3)
    ... 2 lines matching cause stack trace ...
    at async Object.create (file:///C:/Users/leroy/AppData/Local/npm-cache/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/lib/create/index.js:29:11)
    at async bin (file:///C:/Users/leroy/AppData/Local/npm-cache/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/lib/bin/index.js:67:36)
    at async file:///C:/Users/leroy/AppData/Local/npm-cache/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/bin/index.js:4:20 {
  [cause]: Error: Command failed with exit code 1: chmod ug+x .husky/pre-commit
  'chmod' is not recognized as an internal or external command,
  operable program or batch file.
      at makeError (file:///C:/Users/leroy/AppData/Local/npm-cache/_npx/4aa729db9999bfc4/node_modules/execa/lib/error.js:60:11)
      at handlePromise (file:///C:/Users/leroy/AppData/Local/npm-cache/_npx/4aa729db9999bfc4/node_modules/execa/index.js:124:26)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async writeStructure (file:///C:/Users/leroy/AppData/Local/npm-cache/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/lib/steps/writing/writeStructure.js:6:3)
      at async file:///C:/Users/leroy/AppData/Local/npm-cache/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/lib/create/createWithOptions.js:16:9
      at async withSpinners (file:///C:/Users/leroy/AppData/Local/npm-cache/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/lib/shared/cli/spinners.js:28:7)
      at async createWithOptions (file:///C:/Users/leroy/AppData/Local/npm-cache/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/lib/create/createWithOptions.js:12:3)
      at async run (file:///C:/Users/leroy/AppData/Local/npm-cache/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/lib/create/index.js:31:34)
      at async runOrRestore (file:///C:/Users/leroy/AppData/Local/npm-cache/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/lib/shared/runOrRestore.js:7:5)
      at async Object.create (file:///C:/Users/leroy/AppData/Local/npm-cache/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/lib/create/index.js:29:11) {
    shortMessage: 'Command failed with exit code 1: chmod ug+x .husky/pre-commit',
    command: 'chmod ug+x .husky/pre-commit',
    escapedCommand: 'chmod "ug+x" ".husky/pre-commit"',
    exitCode: 1,
    signal: undefined,
    signalDescription: undefined,
    stdout: '',
    stderr: "'chmod' is not recognized as an internal or external command,\r\n" +
      'operable program or batch file.',
    cwd: 'D:\\Users\\Leroy\\Documents\\coding-tutorials\\test-create-ts-app',
    failed: true,
    timedOut: false,
    isCanceled: false,
    killed: false
  }
}
```

### Additional Info

I am running on Windows 11, yet I see that the script is attempting to run the Unix 'chmod' command.

**Comment by JoshuaKGoldberg** [comment]
👋 thanks for filing @lcforbes! Good spot on the `chmod` command. 

https://github.com/JoshuaKGoldberg/create-typescript-app/blob/b465f787923437929ebb2b1ce4474b8f0d2ee122/src/steps/writing/writeStructure.ts#L11

Amusingly, that line of code has been there for several months without issue till now (https://github.com/typicode/husky/issues/1177 -> #718 -> #719). Looks like this package isn't getting used on Windows at all.

Looks like that might not be necessary on Windows at all. Just if you move to or start with a *nix system. I'll send a quick fix to wrap the command in a try/catch. 

Aside: I edited your post to wrap the pasted terminal output as a [code block with <code>```</code>](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code). It's a bit easier for readability. 🙂

**Comment by JoshuaKGoldberg** [comment]
@all-contributors please add @lcforbes for bug.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙
