### ISSUE TITLE
🐛 Bug: SyntaxError on description with regexp characters

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/create-typescript-app#803]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Setup scripts such as `--mode migrate` should be able to plop in descriptions with special characters like `^` and `$`.

### Actual

```plaintext
┌  Welcome to create-typescript-app ! 🎉
│
│  ⚠️ This template is early stage, opinionated, and not endorsed by the TypeScript team. ⚠️
│  ⚠️ If any tooling it sets displeases you, you can always remove that portion manually. ⚠️
│
◇  What organization or user will the repository be under?
│  JoshuaKGoldberg
│
◇  What will the kebab-case name of the repository be?
│  eslint-plugin-expect-type
│
◇  ✅ Passed checking GitHub authentication.
│
◇  How would you describe the new package?
│  ESLint plugin with ^? Twoslash, $ExpectError, and $ExpectType type assertions. 🧩
│
◇  What will the Title Case title of the repository be?
│  eslint-plugin-expect-type
│
◇  Migrating repository structure...
│   - Clearing unnecessary files ✔️
│   - Writing structure ✔️
│   - Writing README.md ✔️
│   - Updating local files.│  ❌ Error migrating repository structure > updating local files.
│
Error: Failed migrating repository structure > updating local files
    at withSpinners (file:///Users/josh/.npm/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/lib/shared/cli/spinners.js:42:11)
    at async migrateWithOptions (file:///Users/josh/.npm/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/lib/migrate/migrateWithOptions.js:15:3)
    ... 4 lines matching cause stack trace ...
    at async file:///Users/josh/.npm/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/bin/index.js:4:20 {
  [cause]: SyntaxError: Invalid regular expression: /ESLint plugin with ^? Twoslash, $ExpectError, and $ExpectType type assertions. 🧩/g: Nothing to repeat
      at new RegExp (<anonymous>)
      at updateLocalFiles (file:///Users/josh/.npm/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/lib/steps/updateLocalFiles.js:31:7)
      at async file:///Users/josh/.npm/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/lib/migrate/migrateWithOptions.js:32:9
      at async withSpinners (file:///Users/josh/.npm/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/lib/shared/cli/spinners.js:28:7)
      at async migrateWithOptions (file:///Users/josh/.npm/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/lib/migrate/migrateWithOptions.js:15:3)
      at async run (file:///Users/josh/.npm/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/lib/migrate/index.js:19:9)
      at async runOrRestore (file:///Users/josh/.npm/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/lib/shared/runOrRestore.js:7:5)
      at async Object.migrate (file:///Users/josh/.npm/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/lib/migrate/index.js:17:11)
      at async bin (file:///Users/josh/.npm/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/lib/bin/index.js:44:29)
      at async file:///Users/josh/.npm/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/bin/index.js:4:20
}
│
◇  Do you want to restore the repository to how it was?
│  No
│
●  Tip: to run again with the same input values, use: npx create-typescript-app --mode migrate --author JoshuaKGoldberg --base everything --description "ESLint plugin with ^? Twoslash, $ExpectError, and $ExpectType type assertions. 🧩" --email npm@joshuakgoldberg.com --owner JoshuaKGoldberg --repository eslint-plugin-expect-type --title eslint-plugin-expect-type
│
└  Operation cancelled. Exiting - maybe another time? 👋
```

### Additional Info

Discovered working on https://github.com/JoshuaKGoldberg/eslint-plugin-expect-type/issues/70.

**Comment by JoshuaKGoldberg** [comment]
Interestingly, I think there are _two_ touch points that make this a nontrivial issue:

* The _input_ regular expression in `updateLocalFiles` needs escaping.
    * I was able to use [`escape-string-regexp`](https://www.npmjs.com/package/escape-string-regexp) for this.
* The _output_ description also needs some kind of escaping or swapping from regexp to plain text.
    * It kept getting printed as `ESLint plugin with ^? Twoslash, , and  type assertions. 🧩` (note the lack of $-prefixed words)...

**Comment by JoshuaKGoldberg** [comment]
Properly escaping `$`s in the description on the CLI actually fixed the latter.

```plaintext
node ~/repos/create-typescript-app/bin/index.js --mode migrate --author JoshuaKGoldberg --base everything --description "ESLint plugin with ^? Twoslash, \$ExpectError, and \$ExpectType type assertions. <0001f9e9>" --email npm@joshuakgoldberg.com --owner JoshuaKGoldberg --repository eslint-plugin-expect-type --title eslint-plugin-expect-type --skip-github-api --exclude-contributors --skip-install
```
